version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "develop"
    directories:
      - "/"
      - "/package/lib/"
    schedule:
      interval: "daily"
    groups:
      splunk:
        applies-to: version-updates
        patterns:
          - "splunk*"
    open-pull-requests-limit: 10
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
