[agile_rates]
python.version = python3
python.required = 3.9

[meter_readings]
python.version = python3
python.required = 3.9

[live_readings]
python.version = python3
python.required = 3.9

[intelligent_octopus]
python.version = python3
python.required = 3.9

